info:
  name: criando um tarefa
  type: http
  seq: 2

http:
  method: POST
  url: "{{baseUrl}}/tasks/create"
  body:
    type: json
    data: |-
      {
        "name": "quarta task",
        "calories": 400,
        "distance": 1,
        "inscriptionId": 1,
        "environment": "livre",
        "duration": 1800,
        "date": "2026-06-05T14:30:00Z",
        "local": "São Paulo"
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
